Update inception_eval.py
I believe there is an error on line 73. 

According to [documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py), tf.train.get_checkpoint_state, which is called on line 66, prepends checkpoint_dir when a relative path to the model is used. On the other hand, line 73 tries to join returned ckpt.model_checkpoint_path and FLAGS.checkpoint_dir. This results with an invalid directory for the saved model.

For example, in my case, the model is saved in ./data/inception-v3-myModel. First line of the Checkpoint file in ./data/inception-v3-myModel is as follows : model_checkpoint_path: "model.ckpt-10000". During execution, tf.train.get_checkpoint_state on line 66
returns ckpt.model_checkpoint_path = 'data/inception-v3-myModel/model.ckpt-10000', so the line 73, which tries to join 'data/inception-v3-myModel/model.ckpt-10000' and 'data/inception-v3-myModel/' leads to the following error:
```
raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: data/inception-v3-myModel/data/inception-v3-myModel
```

NOTE,

Alternative solution, instead of accepting the proposed changes you can also change README.md in the inception project such that checkpoint_dir="${TRAIN_DIR} for the evaluation contains full path to the (chosen) model.